ПРАКТИЧНА РОБОТА 1. 
Вступ до машинного навчання. Елементи лінійної алгебри. 

Номер варіанту: 17
Роботу виконав: Плескач Матвій Русланович
ФІТ 4-6

In [1]:
import numpy as np

1.Створіть одновимірний масив (вектор) з числами, які є квадратами натуральних чисел, починаючи з 1, та виведіть його значення.

In [38]:
a = np.arange(1, 11)** 2
print(a)

[  1   4   9  16  25  36  49  64  81 100]


2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями добутків найближчих менших простих чисел для кожного натурального числа, починаючи з 1, та виведіть його значення.

3.Створіть масив розміром 8x8, заповніть його випадковими натуральними числами від 1 до 10 та знайдіть середнє гармонічне його елементів.
hmeam - harmonic_mean (середнє гармонічне)

In [18]:
from scipy.stats import hmean
m = np.random.randint(1, 11, (8,8))
print("Harmonic mean")
print(hmean(m))

Harmonic mean
[2.19035202 3.42507645 4.38356164 2.50652742 4.13199426 3.32179931
 2.84866469 2.82076396]


4.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 10 та знайдіть вектор-стовпчик, що містить мінімальні елементи в кожному рядку.

In [3]:
m = np.random.uniform(0,10, (3, 3))
print("Matrix")
print(m)
min_elements = np.min(m, axis=1)
print("Min Ele")
print(min_elements)

Matrix
[[7.01582459 1.72531908 0.08521983]
 [5.33403569 3.69014753 8.41524948]
 [8.20186474 7.4723505  1.06188028]]
Min Ele
[0.08521983 3.69014753 1.06188028]


5.Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання ta множення

In [14]:
m1 = np.random.rand(6)
m2 = np.random.rand(6)
print("mass1 = ", m1)
print("mass2 = ", m2)

print("mass1 + mass2 = ", m1 + m2)
print("mass1 - mass2 = ", m1 - m2)
print("mass1 * mass2 = ", m1 * m2)

mass1 =  [0.87071542 0.73124335 0.31735579 0.56672114 0.03559767 0.1929535 ]
mass2 =  [0.66660294 0.17830386 0.81616089 0.42522086 0.62946655 0.98188942]
mass1 + mass2 =  [1.53731836 0.90954721 1.13351668 0.991942   0.66506422 1.17484292]
mass1 - mass2 =  [ 0.20411247  0.55293948 -0.49880509  0.14150028 -0.59386888 -0.78893592]
mass1 * mass2 =  [0.58042146 0.13038351 0.25901339 0.24098165 0.02240754 0.189459  ]


6.Створіть два вектори розміром 8, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [13]:
v1 = np.array([6, 9, 6, 1, 7, 7, 8, 1])
v2 = np.array([8, 9, 5, 7, 4, 7, 3, 3])

dot_v1_v2 = np.dot(v1, v2)

print("vec1 = ", v1)
print("vec2 = ", v2)
print("Scalar prod", dot_v1_v2)

vec1 =  [6 9 6 1 7 7 8 1]
vec2 =  [8 9 5 7 4 7 3 3]
Scalar prod 270


7.Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та перемножте їх між собою

In [43]:
m1 = np.random.randint(1, 20, size=(3, 2))
m2 = np.random.randint(1, 20, size=(2, 4))

dot_m1_m2 = np.dot(m1, m2)

print("matrix1 = ", m1)
print("matrix2 = ", m2)
print("Result")
print(dot_m1_m2)

matrix1 =  [[ 3 16]
 [16 13]
 [16  4]]
matrix2 =  [[15  5  3 10]
 [ 3  7 14  3]]
Result
[[ 93 127 233  78]
 [279 171 230 199]
 [252 108 104 172]]


8.Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.

In [23]:
m = np.random.randint(1, 9, size=(2, 2))
print("Output matrix:")
print(m)
if np.linalg.det(m) == 0:
    print("Can't be inverse")
else:
    inv_m = np.linalg.inv(m)
    print("Inversed matrix")
    print(inv_m)


Output matrix:
[[4 2]
 [2 7]]
Inversed matrix
[[ 0.29166667 -0.08333333]
 [-0.08333333  0.16666667]]


9.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

In [24]:
m = np.random.rand(3, 3)
m_transp = np.transpose(m)
print(m)
print("Transposed matrix")
print(m_transp)

[[0.09972266 0.6122542  0.66799516]
 [0.11432875 0.9943723  0.9849545 ]
 [0.2039491  0.84898478 0.02477567]]
Transposed matrix
[[0.09972266 0.11432875 0.2039491 ]
 [0.6122542  0.9943723  0.84898478]
 [0.66799516 0.9849545  0.02477567]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор. 

In [25]:
m = np.random.rand(3, 4)
v = np.random.randint(1, 11, 4)
print("Matrix")
print(m)
print("Vector:")
print(v)

print("Result matrix * vecotr")
print(np.dot(m,v))

Matrix
[[0.07821042 0.82498202 0.75656365 0.70078104]
 [0.86595732 0.10854643 0.89783701 0.03354522]
 [0.45473481 0.0539255  0.21038296 0.09203637]]
Vector:
[ 5 10  7  1]
Result matrix * vecotr
[14.63759885 11.73365518  4.37764614]


11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму елементів матриці, які більше середнього значення вектору.

In [27]:
m = np.random.randint(1, 11, size = (2,3))
v = np.random.randint(1, 11, 3)
avg_v = np.mean(v)
print (avg_v)
result = np.sum(m[m > avg_v])
print (result)

4.333333333333333
41


12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів діагоналі першої матриці.

In [28]:
m1 = np.random.randint (1, 11, size = (2,2))
m2 = np.random.randint (1, 11, size = (2,2))
print("Diagonal 1st matrix")
print(np.diagonal(m1))
print(sum(np.diagonal(m1)))

Diagonal 1st matrix
[9 7]
16


13.Створіть дві матриці розміром 9x9, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму їх елементів.

In [54]:
m1 = np.random.rand(9, 9)
m2 = np.random.rand(9, 9)
print(sum(m1) + sum(m2))

[ 9.29925187  8.46216118 11.02932008  9.01245948 11.75226678  8.96786785
  8.23615434  9.27394759  8.99838697]


14.Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть середнє геометричне значення елементів матриці. 

In [7]:
from scipy.stats import gmean
m = np.random.uniform (-10, 11, size = (9,9))
print("gmean")
print(gmean([m]))

gmean
[[        nan  7.50884512  4.54398011         nan  3.41510711  3.54374896
          nan  6.8411767   4.85200181]
 [        nan  6.13669552         nan  1.06180002         nan  7.77288964
   5.24315769 10.97536493  7.0484043 ]
 [ 6.62427755  3.53538554  1.26161029  9.66573174  0.44878613  7.5664206
          nan  1.28539074  5.36740305]
 [ 9.97375388 10.5029717   9.4443928   7.48380254  0.56522665         nan
   9.34902256  7.82202813         nan]
 [ 8.7492432   3.54384453         nan  0.31338874         nan  5.0542723
   4.82929467 10.16780204  1.71907801]
 [        nan         nan         nan         nan  5.28415051         nan
          nan  1.64641605         nan]
 [10.68712389         nan         nan  7.88642473  1.96757858  1.61031508
          nan  2.94826541         nan]
 [        nan  3.39030129         nan  3.10291199         nan         nan
   7.7083135          nan         nan]
 [ 1.76268169  2.93716475  9.27974774  8.67346305         nan  9.3991589
   7.07313849 10.90

15.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить кількість додатних елементів в кожному рядку матриці.

In [12]:
m = np.random.rand(3,3)
print (np.sum(m > 0, axis=1))

[3 3 3]


Висновок: Під час виконання практичної роботи, отримав навички зі створення матриць, масивів, векторів заповненими випадковими числами, за допомогою функцій  np.random.rand ( генерує випадкові числа з рівномірним розподілом на інтервалі [0, 1).) . np.random.randint (генерує випадкові цілі числа в заданому діапазоні). Навчився знаходити середнє гармонічне за допомогою імпорту бібліотеки SciPy (для обчислення гармонічного середнього значення), знаходження вектор-стовпчик, що містить мінімальні елементи в кожному рядку, по елементні операції додавання, віднімання тa множення масивів, знаходження оберненої та транспонованої матриці.